### PR TITLE
Screen wraps GLFW::Window.

### PR DESCRIPTION
**Pull request by archSeer**
WIP

### CODE REVIEW

**Comment by archSeer** [comment]
GLFW is an implementation detail, so let's abstract it away. In the case of webGL, we'll instead be creating a canvas internally for example.

**Comment by IceDragon200** [comment]
Good stuff here, lemme test it and get back to you

**Comment by archSeer** [comment]
Alright :) We should wrap some of the glfw methods we use, maybe import a delegator.

**Comment by IceDragon200** [comment]
We could port CRuby's delegate class to mruby and make it a mruby gem.
:package: `mruby-delegate`

**Comment by IceDragon200** [comment]
Here we
:gem: [mruby-delegatable](https://github.com/IceDragon200/mruby-delegatable)

**Comment by archSeer** [comment]
@IceDragon200 good stuff! :+1: :+1: :shipit:

**Pull request merged**
